# 端口
server:
  port: 4444

# 应用名称
spring:
  application:
    name: yunting-center

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname:  ${spring.cloud.client.ipAddress}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    # 是否向注册中心注册自己
    registerWithEureka: true
    # 是否向注册中心获取注册信息
    fetchRegistry: false
    serviceUrl:
      # 注册中心地址
      defaultZone: http://192.168.206.200:8888/eureka/